### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by herkyl** [bcicen/grmon#8]
When running `grmon` I'm getting this error. Any ideas why this is happening?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1385f7c]

goroutine 1 [running]:
main.ReadRoutines(0xc000228000, 0xa1, 0x200, 0x10, 0xff, 0x0, 0x0, 0x0)
	/Users/me/go/src/github.com/bcicen/grmon/parse.go:76 +0x19c
main.poll(0x105a2f0, 0x0, 0xc0000f9ec0, 0xc0001ae000, 0x0)
	/Users/me/go/src/github.com/bcicen/grmon/client.go:38 +0x17c
main.Refresh()
	/Users/me/go/src/github.com/bcicen/grmon/main.go:38 +0x26
main.main()
	/Users/me/go/src/github.com/bcicen/grmon/main.go:202 +0xe7
```

**Comment by bcicen** [comment]
fix added to ignore leading lines prior to goroutine block here in https://github.com/bcicen/grmon/commit/6c3770b6af49c799bb44af4f1029db5de60b41b1

**Comment by herkyl** [comment]
Thank you @bcicen , works as a charm!
